# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost:7272
@content-type=application/json

@token=GCmmSVO7EdCfq9xMRuVR1JAKiJwqo7/n1MOjNPcUXm6sET/ULIF6Hk1wUpanOYBN9zVqA5xwGDfhGH2tGNU8KB7tzAByYl5xGeNNXEqKdILKZJeF0iOBIBfModVOnTZ7QuBRhc0FfxvBK32jZ5i96o61vwIwSEa1I+QtaG2W4gU=
@participantId=6446d1da-e59c-4fdd-9692-30d7a1f1b717

# @token=RhZiRPQuV/BUwPPUG7NvzAPeqJQP6rNjWF5UmCUkRnYSu3jf+6QRLvr6ohMmaEF4acGG1CjAeVV8eIn83EknyLtN2ZjBK8cQd8effOCieR1+3D76OQ6y+/HIouagmguXF1Dqh31hqbNuK/6U/9DZ+ILeBhc5yY+lV0TqH8NkkEY=
# @participantId=f9685fb7-d06b-4822-bd2d-bb90f7d20d98

###

POST {{host}}/api/user/login
Content-Type: {{content-type}}

{
    "userName": "string2",
    "password": "string2"
}

###
POST {{host}}/api/user/register
Content-Type: {{content-type}}

{
  "userName": "string2",
  "password": "string2"
}
###

POST {{host}}/api/messages
Authorization: Bearer {{token}}
Content-Type: {{content-type}}

{
  "receiverId": "{{participantId}}",
  "content": "aasdasdasdsd"
}

###
@since=2023-12-12
GET {{host}}/api/Messages/{{participantId}}?Since={{since}}
Authorization: Bearer {{token}}